@startuml

title __TASK5's Class Diagram__\n

  namespace  {
    namespace ask5 {
      class Task5.Line {
          ~ length : double
          + Line()
          + Line()
          + toString()
          ~ area()
          ~ draw()
      }
    }
  }
  

  namespace  {
    namespace ask5 {
      class Task5.Lines {
          ~ length1 : double
          ~ length2 : double
          + Lines()
          + Lines()
          + toString()
          ~ area()
          ~ draw()
      }
    }
  }
  

  namespace  {
    namespace ask5 {
      class Task5.Pentagon {
          ~ length : double
          + Pentagon()
          + Pentagon()
          + toString()
          ~ area()
          ~ draw()
      }
    }
  }
  

  namespace  {
    namespace ask5 {
      class Task5.Rectangle {
          ~ length : double
          ~ width : double
          + Rectangle()
          + new_rec_fill()
          + new_rec_set()
          + toString()
          ~ area()
          ~ draw()
      }
    }
  }
  

  namespace  {
    namespace ask5 {
      abstract class Task5.Shape {
          # color : Color
          # x : double
          # y : double
          + Shape()
          + setColor()
          {abstract} ~ area()
          {abstract} ~ draw()
      }
    }
  }
  

  namespace  {
    namespace ask5 {
      class Task5.ShapeFactory {
          + createShape()
      }
    }
  }
  

  namespace  {
    namespace ask5 {
      class Task5.Square {
          ~ length : double
          + Square()
          + Square()
          + toString()
          ~ area()
          ~ draw()
      }
    }
  }
  

  namespace  {
    namespace ask5 {
      class Task5.Triangle {
          ~ length : double
          + Triangle()
          + Triangle()
          + toString()
          ~ area()
          ~ draw()
      }
    }
  }
  

  Task5.Line -up-|> Task5.Shape
  Task5.Lines -up-|> Task5.Shape
  Task5.Pentagon -up-|> Task5.Shape
  Task5.Rectangle -up-|> Task5.Shape
  Task5.Square -up-|> Task5.Shape
  Task5.Triangle -up-|> Task5.Shape


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
